#pragma once

enum class MyErrors {
	ERROR_OPEN_PROCESS=1,
	ERROR_ENUM_PROCESSES,
	ERROR_ENUM_PROC_MODULES,
	ERROR_LOAD_NT_FUNC,
	ERROR_QUERY_SYS_INFO,
	ERROR_QUERY_PROC_INFO,
	ERROR_QUERY_OBJ,
	ERROR_DUPLICATE_HANDLE,
	ERROR_READ_PROC_MEM,
	ERROR_VIRTUAL_ALLOC,
	ERROR_VIRTUAL_FREE,

};
