#pragma once

enum MyErrors {
	ERROR_OPEN_PROCESS=1,
	ERROR_ENUM_PROCESSES,
	ERROR_ENUM_PROC_MODULES,
	ERROR_GET_MODULE_HANDLE,
	ERROR_GET_PROC_ADDR,
	ERROR_QUERY_SYS_INFO,
	ERROR_QUERY_PROC_INFO,
	ERROR_QUERY_OBJ,
	ERROR_DUPLICATE_HANDLE,
	ERROR_READ_PROC_MEM,
	ERROR_VIRTUAL_ALLOC,
	ERROR_VIRTUAL_FREE,
	ERROR_VIRTUAL_FREE_NULLPTR
};
